version: '3.7'

services:
  mongodb:
    container_name: MongoBibleText
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./volume-mongo-data/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /data/db
      - /data/config
    networks:
      - bibletext-network

  elasticsearch:
    container_name: ElasticSearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ./volume-elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - bibletext-network

  kibana:
    container_name: Kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - bibletext-network

  bibletextbot.worker:
    container_name: BotWorkerBibleText
    image: ${DOCKER_REGISTRY-}bibletextbotworker
    restart: on-failure
    build:
      context: .
      dockerfile: src/BibleTextBot.Worker/Dockerfile
    depends_on:
      - mongodb
    networks:
      - bibletext-network

volumes:
  volume-mongo-data:
    driver: local
  volume-elasticsearch-data:
    driver: local

networks:
  bibletext-network:
    driver: bridge