version: '3.4'

services:
  mongodb:
    container_name: MongoBibleText
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db-bible/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /data/db
      - /data/config
    networks:
      - bibletext-network

  bibletextbot.worker:
    container_name: BotWorkerBibleText
    image: ${DOCKER_REGISTRY-}bibletextbotworker
    restart: on-failure
    build:
      context: .
      dockerfile: src/BibleTextBot.Worker/Dockerfile
    depends_on:
      - mongodb
    networks:
      - bibletext-network


volumes:
  bibletextbot-nosqldata:
    driver: local

networks:
  bibletext-network:
    driver: bridge