version: '3.4'

services:
  bibletextbot.worker:
    image: ${DOCKER_REGISTRY-}bibletextbotworker
    build:
      context: .
      dockerfile: src/BibleTextBot.Worker/Dockerfile
  
  nosqldata:
    image: mongo

volumes:
  bibletextbot-nosqldata:
    external: false